Add additional grid option for expanded AOI
opendatacube/odc-dscache pull request #4
Opened 2024-02-01 05:22 UTC by JM-GA

Sometime later this year an expanded AOI may be rolled out. To anticipate this, a new 30m extended grid option has been added.

2024-02-01 05:31 UTC, robbibt requested changes

2024-02-01 05:31 UTC, robbibt commented on odc/dscache/tools/tiling.py
> +        origin=(-4416000.0, -6912000.0),
GridSpec origins are Y, X, so I think this needs to be reversed:

```suggestion
        origin=(-6912000.0, -4416000.0),
```

2024-02-01 05:31 UTC, robbibt commented on odc/dscache/tools/tiling.py
> +            origin=(-4416000.0, -6912000.0),
Same here:

```suggestion
        origin=(-6912000.0, -4416000.0),
```

2024-02-01 05:41 UTC, robbibt approved these changes
Looks great - have tested the updated geobox and the 0, 0 tile is where I would expect:

![image](https://github.com/opendatacube/odc-dscache/assets/17680388/5d3574d4-5458-44a5-8d0c-d6e59bf05ab5)

```
from datacube.model import GridSpec
import geopandas as gpd

gs = GridSpec(
        crs='epsg:3577',
        tile_size=(96_000.0, 96_000.0),
        resolution=(-96_000, 96_000),
        origin=(-6912000.0, -4416000.0))

gpd.GeoSeries(gs.tile_geobox([0, 0]).geographic_extent.geom).to_file("test.geojson")
```

2024-02-01 05:51 UTC, JM-GA commented
Thanks @robbibt !

2024-02-02 00:18 UTC, emmaai approved these changes

2024-02-02 02:36 UTC, merged